In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(a + a)

[1 2 3 4]
[2 4 6 8]


In [2]:
b = [1,2,3,4]
print(b + b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [11]:
a = np.array([[[1,2], [3,4]], [[1,2], [3,4]]])
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [21]:
a = np.array([[1,2], [3,4]])
print(a)

[[1 2]
 [3 4]]


In [22]:
a = np.array([[[1,2], [3,4]], [[1,2], [3,4]]])
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [23]:
a = np.array([1,2,3,4])
b = np.array([[1], [2], [3], [4], [5]])
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [24]:
import numpy as np
from numpy import linalg as LA
c = np.array([[1, 2, 3],
            [-1, 1, 4]])
print(LA.norm(c, axis=0))
print(LA.norm(c, axis=1))
print(LA.norm(c, ord=1, axis=1))
print(LA.norm(c, ord=2, axis=1))

[1.41421356 2.23606798 5.        ]
[3.74165739 4.24264069]
[6. 6.]
[3.74165739 4.24264069]


In [30]:
a = np.array([[1], [2], [3], [4]])
print(a) #shape = (4,1)
print(a.T) # shape = (1,4)
print(a.T.reshape(-1, 4))
print(a.shape)
print(a.T.reshape(-1, 4).T.shape)

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
[[1 2 3 4]]
(4, 1)
(4, 1)


In [31]:
a = np.array([10,20,30,40,50,60])
print(a)
b = a[[4,2,0]]
print(b)
idx = np.arange(0, len(a))
print(idx)
np.random.shuffle(idx)
print(idx)
print(a[idx])

[10 20 30 40 50 60]
[50 30 10]
[0 1 2 3 4 5]
[5 0 2 4 1 3]
[60 10 30 50 20 40]


In [32]:
import numpy as np
c = np.array([1,2,3,4,5,6])
print(c[0])
print(c[5])
print(c[-1])
print(c[-2])
print(c[-6])
print(c[0:2])
print(c[2:5])
print(c[:2])
print(c[4:])
print(c[-2:])
print(c[:2], c[2:])
print(c[:4], c[4:])
print(np.arange(5,10))

1
6
6
5
1
[1 2]
[3 4 5]
[1 2]
[5 6]
[5 6]
[1 2] [3 4 5 6]
[1 2 3 4] [5 6]
[5 6 7 8 9]


In [33]:
word = 'Python'
print(word[0])
print(word[5])
print(word[-1])
print(word[-2])
print(word[-6])
print(word[0:2])
print(word[2:5])
print(word[:2])
print(word[4:])
print(word[-2:])
print(word[:2] + word[2:])
print(word[:4] + word[4:])

P
n
n
o
P
Py
tho
Py
on
on
Python
Python
