In [6]:
import numpy as np
A = np.array([[1, 4, 2, 0], [9, 5, 0, 0], [4, 0, 2, 4], [6, 1, 8, 3]])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n = 4
for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        val += A[i,j] + x[j]
        b[i] = val
print("calculate =", b)

b= np.dot(A,x)
print("dot=", b)

b= np.matmul(A,x)
print("matmul=", b)

b = A@x
print("A@x=", b)

b = A*x
print("A*x=", b)

calculate = [17 24 20 28]
dot= [15 19 26 44]
matmul= [15 19 26 44]
A@x= [15 19 26 44]
A*x= [[ 1  8  6  0]
 [ 9 10  0  0]
 [ 4  0  6 16]
 [ 6  2 24 12]]


In [13]:
import numpy as np
A = np.array([[1,4,2,0],[9,5,0,0], [4,0,2,4], [6,1,8,3]])
b = np.array([15, 19, 26, 44])

print("det", np.linalg.det(A))

x = np.linalg.solve(A,b)
print("solver =", x)

x = np.dot(np.linalg.inv(A),b)
print("inverse1 =" ,x)

tmp_b = np.dot(A.T,b)
tmp_T = np.dot(A.T,A)
tmp_inv = np.linalg.inv(np.dot(A.T,A))
x = np.dot(tmp_inv,tmp_b)
print("inverse2", x)

det 853.9999999999995
solver = [1. 2. 3. 4.]
inverse1 = [1. 2. 3. 4.]
inverse2 [1. 2. 3. 4.]
