In [17]:
# 넘파이 배열
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(a+a)

[1 2 3 4]
[2 4 6 8]


In [6]:
# 일반 배열
b = [1,2,3,4]
print(b+b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [8]:
# 이중 배열(행렬)
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [13]:
# 삼중 배열(행렬)
a= np.array([[[1,2],[3,4]], [[1,2],[3,4]]])
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [14]:
# 형태
a = np.array([1,2,3,4])
b = np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [16]:
import numpy as np
from numpy import linalg as LA
c = np.array([[1,2,3,],[-1,1,4]])
print(LA.norm(c, axis = 0))
print(LA.norm(c, axis = 1))
print(LA.norm(c, ord = 1,axis = 1))
print(LA.norm(c, ord = 2,axis = 1))

[1.41421356 2.23606798 5.        ]
[3.74165739 4.24264069]
[6. 6.]
[3.74165739 4.24264069]


In [24]:
# 전치 연산(Transpose)
a = np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)
print('===================================')
print(a.T)
print(a.T.shape)
print('===================================')
# 4열로 지정 후 행은 알아서 지정(-1은 알아서 지정해주라는 뜻)
print(a.T.reshape(-1,4))
print(a.shape)
print('===================================')
print(a.T.reshape(-1,4).T.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[1 2 3 4]]
(1, 4)
[[1 2 3 4]]
(4, 1)
(4, 1)


In [28]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(3,2))
print(a.shape)
print('===================================')
b = a.reshape(3,-1)
print(b)
print(b.shape)
print('===================================')
c = a.reshape(-1,2)
print(c)
print(c.shape)

[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [34]:
a = np.array([[1,2,3,4]])
print(a)
print(a.T)
print(a.T.shape)
print('===================================')
b = a.reshape(4,-1)
print(b.shape)
print(b)
print(b.T)
print(b.T.shape)
print('===================================')
c = np.array([1,2,3,4])
print(c)
print(c.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
(4, 1)
(4, 1)
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
(1, 4)
[1 2 3 4]
[1 2 3 4]


In [25]:
# 배열 인덱싱
a = np.array([10,20,30,40,50,60])
print(a)
print('===================================')
b = a[[4,2,0]]
print(b)
print('===================================')
idx = np.arange(0,len(a))
print(idx)
print('===================================')
np.random.shuffle(idx)
print(idx)
print(a[idx])

[10 20 30 40 50 60]
[50 30 10]
[0 1 2 3 4 5]
[4 5 2 3 1 0]
[50 60 30 40 20 10]


In [27]:
import numpy as np
c = np.array([1,2,3,4,5,6])
print(c[0])
print(c[5])
print('===================================')
print(c[-1])
print(c[-2])
print(c[-6])
print('===================================')
print(c[0:2])
print(c[2:5])
print('===================================')
print(c[:2])
print('===================================')
print(c[4:])
print(c[-2:])
print('===================================')
print(c[:2], c[2:])
print(c[:4], c[4:])
print('===================================')
print(np.arange(5,10))

1
6
6
5
1
[1 2]
[3 4 5]
[1 2]
[5 6]
[5 6]
[1 2] [3 4 5 6]
[1 2 3 4] [5 6]
[5 6 7 8 9]


In [36]:
word = 'Python'
print(word[0])
print(word[5])
print('===================================')
print(word[-1])
print(word[-2])
print(word[-6])
print('===================================')
print(word[0:2])
print(word[2:5])
print('===================================')
print(word[:2])
print(word[4:])
print('===================================')
print(word[-2:])
print('===================================')
print(word[:2] + word[2:])
print(word[:4] + word[4:])

P
n
n
o
P
Py
tho
Py
on
on
Python
Python
