In [6]:
import numpy as np
from numpy import random

a=np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [2]:
b = a[[4,2,0]]
print(b)

[50 30 10]


In [3]:
idx = np.arange(0, len(a))
print(idx)

[0 1 2 3 4 5]


In [8]:
np.random.shuffle(idx)
print(idx)
print(a[idx])

[1 4 3 2 5 0]
[20 50 40 30 60 10]


In [9]:
import numpy as np
c = np.array([1,2,3,4,5,6])
print(c[0])

1


In [10]:
print(c[5])

6


In [11]:
print(c[-1])

6


In [12]:
print(c[-2])

5


In [13]:
print(c[-6])

1


In [14]:
print(c[0:2])

[1 2]


In [15]:
print(c[2:5])

[3 4 5]


In [16]:
print(c[:2])

[1 2]


In [17]:
print(c[4:])

[5 6]


In [18]:
print(c[-2:])

[5 6]


In [19]:
print(c[:2], c[2:])

[1 2] [3 4 5 6]


In [20]:
print(np.arange(5,10))

[5 6 7 8 9]
