In [2]:
import numpy as np

a=np.array([[1],[2],[3],[4]])
print(a)

[[1]
 [2]
 [3]
 [4]]


In [3]:
print(a.T)

[[1 2 3 4]]


In [5]:
print(a.T.reshape(-1,4))

[[1 2 3 4]]


In [7]:
print(a.shape)

(4, 1)


In [9]:
print(a.T.reshape(-1,4).T.shape)

(4, 1)
