In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])

print(a)
print (a + a)

b = [1, 2, 3, 4]
print(b + b)

a = np.array([[[1, 2], [3, 4]], [[1, 2], [3, 4]]])
print(a)

a = np.array([1, 2, 3, 4])
b = np.array([[1], [2], [3], [4]])

print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4]
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [4]:
import numpy as np
from numpy import linalg as LA

c = np.array([[1, 2, 3],
              [-1, 1, 4]])

print(LA.norm(c, axis=0))
print(LA.norm(c, axis=1))
print(LA.norm(c, ord=1, axis=1))
print(LA.norm(c, ord=2, axis=1))

[1.41421356 2.23606798 5.        ]
[3.74165739 4.24264069]
[6. 6.]
[3.74165739 4.24264069]


In [8]:
# Transpose

a = np.array([[1], [2], [3], [4]])
print(a)
print(a.T)
print(a.T.reshape(-1, 4))
print(a.shape)
print(a.T.reshape(-1, 4).T.shape)

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
[[1 2 3 4]]
(4, 1)
(4, 1)


In [9]:
# Reshape

a = np.array([1, 2, 3, 4, 5, 6])
print(a.reshape(3, 2))
print(a.shape)

b = a.reshape(3, -1)
print(b)
print(b.shape)

c=a.reshape(-1, 2)
print(c)
print(c.shape)

[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [10]:
a = np.array([1, 2, 3, 4])
print(a)
print(a.T)
b = a.reshape(4, -1)
print(b.shape)
print(b)
print(b.T.shape)

[1 2 3 4]
[1 2 3 4]
(4, 1)
[[1]
 [2]
 [3]
 [4]]
(1, 4)


In [11]:
a = np.array([10, 20, 30, 40, 50, 60])
print(a)
b = a[[4, 2, 0]]
idx = np.arange(0, len(a))
print(idx)
np.random.shuffle(idx)
print(idx)
print(a[idx])

[10 20 30 40 50 60]
[0 1 2 3 4 5]
[4 2 0 1 3 5]
[50 30 10 20 40 60]


In [15]:
import numpy as np
c = np.array([1, 2, 3, 4, 5, 6])
print(c[0])
print(c[5])
print(c[-1])
print(c[-2])
print(c[-6])
print(c[0:2])
print(c[2:5])
print(c[:2])
print(c[4:])
print(c[-2:])
print(c[:2], c[2:])
print(np.arange(5, 10))

1
6
6
5
1
[1 2]
[3 4 5]
[1 2]
[5 6]
[5 6]
[1 2] [3 4 5 6]
[5 6 7 8 9]


In [16]:
word = 'Python'
print(word[0])
print(word[5])
print(word[-1])
print(word[-2])
print(word[-6])
print(word[0:2])
print(word[2:5])
print(word[:2])
print(word[4:])
print(word[-2:])
print(word[2:] + word[:2])

P
n
n
o
P
Py
tho
Py
on
on
thonPy


In [19]:
a = np.array([[1, 4, 2, 0], [9, 5, 0, 0], [4, 0, 2, 4], [6, 1, 0, 3]])
x = np.array([1, 2, 3, 4])
b = np.array([0, 0, 0, 0])
n = 4

for i in range(0, n):
    val = 0.0
    for j in range(0, n):
        val += a[i, j] + x[i]
    b[i] = val

print(a)
print(b)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 0 3]]
[11 22 22 26]
