In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(a+a)

[1 2 3 4]
[2 4 6 8]


In [2]:
b=[1,2,3,4]
print(b+b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [3]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [6]:
a=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [7]:
a=np.array([1,2,3,4])
b=np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [13]:
import numpy as np
from numpy import linalg as LA
c=np.array([[1,2,3],[-1,1,4]])
print(LA.norm(c,axis=0))
print(LA.norm(c,axis=1))
print(LA.norm(c,ord=1,axis=1))
print(LA.norm(c,ord=2,axis=1))

[1.41421356 2.23606798 5.        ]
[3.74165739 4.24264069]
[6. 6.]
[3.74165739 4.24264069]


In [15]:
a=np.array([[1],[2],[3],[4]])
print(a)
print(a.T)
print(a.t.reshape(-1,4))
print(a.shape)
print(a.T.reshape(-1,4).T.shape)

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


In [17]:
a=np.array([1,2,3,4])
b=a.reshape(4,-1)
print(a)
print(a.reshape(2,-1))
print(a.shape,",",b.shape,",",np.array([[1,2,3,4]]).shape)

[1 2 3 4]
[[1 2]
 [3 4]]
(4,) , (4, 1) , (1, 4)


In [18]:
a=np.array([1,2,3,4,5,6])
print(a.reshape(3,2))
print(a.shape)
b=a.reshape(3,-1)
print(b)
print(b.shape)
c=a.reshape(-1,2)
print(c)
print(c.shape)

[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [26]:
a=np.array([1,2,3,4])
print(a)
print(a.T)
b=a.reshape(4,-1)
print(b.shape)
print(b)
print(b.T.shape)

[1 2 3 4]
[1 2 3 4]
(4, 1)
[[1]
 [2]
 [3]
 [4]]
(1, 4)


In [27]:
a=np.array([10,20,30,40,50,60])
print(a)
b=a[[4,2,0]]
print(b)
idx=np.arange(0,len(a))
print(idx)
np.random.shuffle(idx)
print(idx)
print(a[idx])

[10 20 30 40 50 60]
[50 30 10]
[0 1 2 3 4 5]
[0 3 4 2 1 5]
[10 40 50 30 20 60]


In [28]:
c=np.array([1,2,3,4,5,6])
print(c[0])
print(c[5])
print(c[-1])
print(c[-2])
print(c[-6])
print(c[0:2])
print(c[2:5])
print(c[:2])
print(c[4:])
print(c[-2:])
print(c[:2],c[2:])
print(c[:4],c[4:])
print(np.arange(5,10))

1
6
6
5
1
[1 2]
[3 4 5]
[1 2]
[5 6]
[5 6]
[1 2] [3 4 5 6]
[1 2 3 4] [5 6]
[5 6 7 8 9]


In [31]:
word='Python'
print(word[0])
print(word[5])
print(word[-1])
print(word[-2])
print(word[-6])
print(word[0:2])
print(word[2:5])
print(word[:2])
print(word[4:])
print(word[-2:])
print(word[:2] + word[2:])
print(word[:4] + word[4:])

P
n
n
o
P
Py
tho
Py
on
on
Python
Python


In [32]:
A=np.array([[1,4,2,0],[9,5,0,0],[4,0,2,4],[6,1,8,3]])
x=np.array([1,2,3,4])
b=np.array([0,0,0,0])
n=4
for i in range(0,n):
    val = 0.0
    for j in range(0,n):
        val+=A[i,j]*x[j]
    b[i]=val

print("calculate=",b)

b=np.dot(A,x)
print("dot=",b)

b=np.matmul(A,x)
print("matmul=",b)

b=A@x
print("A@x=",b)

b=A*x
print("A*x=",b)

calculate= [15 19 26 44]
dot= [15 19 26 44]
matmul= [15 19 26 44]
A@x= [15 19 26 44]
A*x= [[ 1  8  6  0]
 [ 9 10  0  0]
 [ 4  0  6 16]
 [ 6  2 24 12]]


In [36]:
import numpy as np
A=np.array([[1,4,2,0],[9,5,0,0],[4,0,2,4],[6,1,8,3]])
b=np.array([15,19,26,44])

print("det=",np.linalg.det(A))

x=np.linalg.solve(A,b)
print("solver=",x)

x=np.dot(np.linalg.inv(A),b)
print("inversel=",x)

tmp_b=np.dot(A.T,b)
tmp_T=np.dot(A.T,A)
tmp_inv=np.linalg.inv(np.dot(A.T,A))
x=np.dot(tmp_inv,tmp_b)
print("inverse2 =",x)

det= 853.9999999999995
solver= [1. 2. 3. 4.]
inversel= [1. 2. 3. 4.]
inverse2 = [1. 2. 3. 4.]
